name: localize
description: A new Flutter project.

publish_to: 'none' 

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  firebase_storage: ^12.3.3
  image_picker: ^1.1.2
  cloud_firestore: ^5.4.3
  provider: ^6.0.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_in_app_messaging: ^0.8.0+8
  info_popup: ^4.3.1
  url_launcher: ^6.3.1
  intl: ^0.19.0
  flutter_rating_bar: ^4.0.1
  encrypt: ^5.0.0
  flutter_reaction_button: ^2.0.2 # Use the latest version if available
  ionicons: ^0.2.2
  rating_summary: ^1.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true

  assets:
    - images/Logo.png
    - images/image1.jpg
    - images/Riyadh.webp
    - images/default_profile.png
    - images/Park.png
    - images/Shopping.png
    - images/Restaurant.png
    - images/children.png
