name: admin_panel
description: Custom admin panel
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^9.0.0
  google_fonts: ^6.1.0

flutter:
  assets:
    - assets/images/logo.png